version: "3.8"

services:
  fastapi:
    container_name: shulker-box-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file:
      - ./docker/.env
    volumes:
      - .:/app
    ports:
      - 8003:8003
    stdin_open: true
    tty: true
