version: "3.8"

services:
  fastapi:
    container_name: shulker-box-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file:
      - ./docker/.env
    volumes:
      - .:/app
    ports:
      - 8003:8003
    stdin_open: true
    tty: true

  mongodb:
    container_name: shulker-box-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: items
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27018:27017

# Connect to the oak signs network
# to enable communication between the services
networks:
  default:
    name: oak-signs_default
