version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - .
      - run:
          name: Run pre-commit hooks
          command: make lint

workflows:
  continuous_integration:
    jobs:
      - build-and-test
